version: "3.7"
services:
    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:latest
        ports:
            - "1883:1883"
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
        restart: always
